# Generated by Django 5.2.17 on 2026-08-28 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='traffic_source',
            field=models.CharField(choices=[('direct', 'Direct'), ('google', 'Google (organic)'), ('google_ads', 'Google Ads'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('other', 'Other')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='utm_content',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='utm_source',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='utm_term',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='traffic_source',
            field=models.CharField(choices=[('direct', 'Direct'), ('google', 'Google (organic)'), ('google_ads', 'Google Ads'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('other', 'Other')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_content',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_term',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['traffic_source'], name='leads_lead_traffic_59b69c_idx'),
        ),
    ]
