# Generated by Django 5.1.15 on 2026-08-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_contactrequest_traffic_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='gclid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='gclid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
