# Generated by Django 6.1 on 2026-08-28 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITAuditRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('employee_count', models.CharField(choices=[('1-5', '1–5'), ('6-20', '6–20'), ('21-50', '21–50'), ('51-200', '51–200'), ('200+', '200+')], max_length=20)),
                ('infrastructure', models.JSONField(blank=True, default=list, help_text='Windows, Linux, Cloud, On-premise servers, MikroTik, FortiGate, Cisco, Wi-Fi, CCTV, VPN, Backup, Monitoring')),
                ('problems', models.JSONField(blank=True, default=list, help_text='Network, Security, Servers, Backup, Performance, Support, Other')),
                ('problems_other', models.CharField(blank=True, max_length=300)),
                ('preferred_contact_method', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CONVERTED', 'Converted to client'), ('DISMISSED', 'Dismissed')], default='NEW', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
