# Generated by Django 6.1 on 2026-08-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itauditrequest',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_requests', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='itauditrequest',
            index=models.Index(fields=['status'], name='audits_itau_status_086567_idx'),
        ),
        migrations.AddIndex(
            model_name='itauditrequest',
            index=models.Index(fields=['created_at'], name='audits_itau_created_6007a7_idx'),
        ),
    ]
