# Generated by Django 5.2.17 on 2026-08-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itauditrequest',
            name='traffic_source',
            field=models.CharField(choices=[('direct', 'Direct'), ('google', 'Google (organic)'), ('google_ads', 'Google Ads'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('other', 'Other')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='itauditrequest',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='itauditrequest',
            name='utm_content',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='itauditrequest',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='itauditrequest',
            name='utm_source',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='itauditrequest',
            name='utm_term',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
