# Generated by Django 5.1.15 on 2026-08-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_itauditrequest_traffic_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itauditrequest',
            name='gclid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
