# Generated by Django 6.1 on 2026-08-28 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CONTRACT', 'Contract'), ('REPORT', 'Report'), ('INVOICE', 'Invoice'), ('AUDIT', 'Audit Report'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('file', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
